version: '3'

services:
    pokedexapp:
        depends_on:
            - db
        build: 
            context: .
            dockerfile: Dockerfile
        image: pokedex-docker
        container_name: pokedexapp
        restart: always # reiniciar el contenedor si se detiene
        ports:
            - "${PORT}:${PORT}"
        environment:
            NODE_ENV: ${NODE_ENV}
            MONGODB_HOST: ${MONGODB_HOST}
            PORT: ${PORT}
            PAGINATION_LIMIT: ${PAGINATION_LIMIT}

    db:
        image: mongo:7.0
        container_name: mongo-poke
        restart: always
        ports:
            - 27018:27017
        environment:
            MONGODB_NAME: pokemons
        volumes:
            - ./mongo:/data/db