version: '3'

services:
    db:
        image: mongo:7.0
        restart: always
        ports:
            - 27018:27017
        environment:
            MONGODB_NAME: pokemons
        volumes:
            - ./mongo:/data/db